### ISSUE TITLE
Declaration of getContributionID() causing failed Civi upgrade

### ISSUE THREAD

**Issue by MattTrim1** [mjwconsult/civicrm-userpayment#4]
Hi,

I experienced the below error message when attempting to upgrade a CiviCRM instance from 5.47.4 to 5.49.5 with this extension installed.

"Declaration of CRM_Userpayment_Form_Payment::getContributionID() must be compatible with CRM_Contribute_Form_AbstractEditPayment::getContributionID(): ?int"

I'm not sure when the return type declaration was added in Core but applying a patch to "CRM_Userpayment_Form_Payment::getContributionID()" to include the return type declaration allowed the upgrade to complete smoothly.

I'll raise a PR with the changes I made.

Thanks,
Matt

**Comment by mattwire** [comment]
Thanks @MattTrim1 fixed in 1.3
